### ISSUE TITLE
Something wrong with repo for stone

### ISSUE THREAD

**Issue by Dejal** [dropbox/dropbox-sdk-obj-c#28]
The `stone` item in the repo web view is listed as `stone @ aa400c5`, and shows a 404 when clicked. Cloning the project in GitHub Desktop shows an uncommitted change (that I didn't do):

    - Subproject commit aa400c5a23a2c4822c77c3bcab87703bea4bfa48
    + Subproject commit a69b888936a8a69037cadb72ebb6679efc8d0d8f-dirty

**Comment by scobbe** [comment]
Hmm not sure what went wrong – we'll be posting the full `stone` repo code tomorrow. Right now, the commit hash points to a local commit, not to a remote commit, which might explain your issue. Given that the `stone` code is just for the SDK generation, this hopefully shouldn't block on you on anything. I'll ping this thread when we have an actual reference to a commit on the remote `stone`

**Comment by Dejal** [comment]
Thanks. Possibly related, when I try building my Mac app with the embedded project included (installed via the "**Manually add subproject**" instructions), if I try:

    #import "DropboxSDKImports.h"

I get the error:

    'DropboxSDKImports.h' file not found

If I try:

    #import <ObjectiveDropboxOfficial_OSX/DropboxSDKImports.h>

I get the error:

    Dropbox/Source/ObjectiveDropboxOfficial/PlatformNeutral/DropboxSDKImports.h:13:9: 'DropboxClientsManager+DesktopAuth.h' file not found
    While building module 'ObjectiveDropboxOfficial_OSX'
    <module-includes>:1:9: In file included from <module-includes>:1:
    Dropbox/Source/ObjectiveDropboxOfficial_OSX/ObjectiveDropboxOfficial_OSX.h:19:9: In file included from Build/Debug/ObjectiveDropboxOfficial_OSX.framework/Headers/ObjectiveDropboxOfficial_OSX.h:19

(edited to remove my project paths)

Some lingering `OSX` references there, too.

The **TestObjectiveDropbox_macOS** and **DBRoulette** projects also had different errors.

**Comment by scobbe** [comment]
@Dejal: Thanks for pointing this out. Looks like the refactor from 94ac252 broke the main project. Try pulling the repo again and let me know if it works.

As far as the *DBRoulette* project, it's getting an update tomorrow. The *TestObjectiveDropbox_macOS* should be working now.

Let me know! Thanks for the help.

**Comment by Dejal** [comment]
That seemed to work better.

I had to change the `#import` to:

    #import <ObjectiveDropboxOfficial_macos/DropboxSDKImports.h>

instead of just `#import "DropboxSDKImports.h"` as in the readme.

Also, I get a bunch of warnings like:

    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBAUTHAuthError.h'
    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBAUTHRateLimitError.h'
    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBAUTHRateLimitReason.h'
    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBDelegate.h'
    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBFILESDimensions.h'
    <module-includes>:1:1: Umbrella header for module 'ObjectiveDropboxOfficial_macOS' does not include header 'DBFILESGpsCoordinates.h'

But it builds and seems to work, as far as I've got in updating the app.

**Comment by lvandal** [comment]
Seems like the original issue is back after the latest commit. Carthage fails with this error: 

`A shell task (/usr/bin/env git checkout --quiet 41b599f2636a983d7cf8e59ac4e9a5cacbf02af0) failed with exit code 128:
fatal: reference is not a tree: 41b599f2636a983d7cf8e59ac4e9a5cacbf02af0`

**Comment by scobbe** [comment]
@lvandal @Dejal: Sorry for all the hassle. Been ironing out some kinks. Things should be more stable now.

@Dejal: I think I fixed the umbrella header warnings issue, so let me know if you see that after downloading the latest version.

@Ivandal: the `reference is not a tree` error should be gone as well

As far as imports, going forward, only these import statements are necessary:

`#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>`

(and for macOS)

`#import <ObjectiveDropboxOfficial_macOS/ObjectiveDropboxOfficial_macOS.h>`

Thanks all for your patience. Let me know if you run into any more issues.
